import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Brand
        "ink-navy": "#1A2A3F",
        "stone-white": "#F4F1EC",
        "mortar-grey": "#B8B0A4",
        "muted-azure": "#6B8CAE",
        // Material surface system (from Stitch)
        primary: "#04152a",
        "on-primary": "#ffffff",
        "primary-container": "#1a2a3f",
        "on-primary-container": "#8191ab",
        "on-primary-fixed": "#0b1c31",
        "on-primary-fixed-variant": "#38485e",
        secondary: "#406181",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#cfe5ff",
        "secondary-fixed-dim": "#a8caee",
        "on-secondary-fixed": "#001d33",
        "on-secondary-fixed-variant": "#274968",
        "secondary-container": "#b9daff",
        "on-secondary-container": "#3f6080",
        tertiary: "#141512",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#292926",
        "on-tertiary-container": "#91908c",
        "on-tertiary-fixed": "#1c1c19",
        "on-tertiary-fixed-variant": "#474743",
        "tertiary-fixed": "#e5e2dd",
        "tertiary-fixed-dim": "#c9c6c2",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#fff8f2",
        "on-background": "#1f1b13",
        surface: "#fff8f2",
        "on-surface": "#1f1b13",
        "on-surface-variant": "#44474d",
        "surface-variant": "#eae1d4",
        "surface-dim": "#e2d9cc",
        "surface-bright": "#fff8f2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fcf2e5",
        "surface-container": "#f6eddf",
        "surface-container-high": "#f0e7da",
        "surface-container-highest": "#eae1d4",
        "inverse-surface": "#343027",
        "inverse-on-surface": "#f9efe2",
        "inverse-primary": "#b7c7e3",
        "primary-fixed": "#d3e3ff",
        "primary-fixed-dim": "#b7c7e3",
        outline: "#74777d",
        "outline-variant": "#c4c6cd",
        "surface-tint": "#505f77",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "margin-edge": "40px",
        "section-gap": "120px",
        baseline: "4px",
        "container-max": "1440px",
        gutter: "24px",
      },
      fontFamily: {
        serif: ["var(--font-newsreader)", "Georgia", "serif"],
        sans: ["var(--font-manrope)", "system-ui", "sans-serif"],
        "stat-display": ["var(--font-newsreader)", "Georgia", "serif"],
        "label-caps": ["var(--font-manrope)", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["var(--font-newsreader)", "Georgia", "serif"],
        "body-md": ["var(--font-manrope)", "system-ui", "sans-serif"],
        "display-hero": ["var(--font-newsreader)", "Georgia", "serif"],
        "headline-md": ["var(--font-newsreader)", "Georgia", "serif"],
        "body-lg": ["var(--font-manrope)", "system-ui", "sans-serif"],
        "headline-lg": ["var(--font-newsreader)", "Georgia", "serif"],
      },
      fontSize: {
        "stat-display": ["64px", { lineHeight: "64px", fontWeight: "300" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg-mobile": ["36px", { lineHeight: "44px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "display-hero": ["84px", { lineHeight: "92px", letterSpacing: "-0.02em", fontWeight: "300" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "30px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
