import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Light base canvas, deep navy accents (see docs/MASTER-PLAN.md §4)
        "ink-navy": "#0f1a2e",
        "ink-deep": "#0a1220",
        "ink-mid": "#162035",
        "stone-white": "#f4f1ec",
        "mortar-grey": "#6b7280",
        "mortar-light": "#9ca3af",
        "muted-azure": "#7b9ec4",
        "muted-azure-dim": "#4a6d94",
        "cream": "#f5f0e8",
        "cream-dim": "#d4cfc6",
        // Surface system (dark)
        primary: "#0a1220",
        "on-primary": "#f5f0e8",
        "primary-container": "#162035",
        "on-primary-container": "#9ca3af",
        "on-primary-fixed": "#f5f0e8",
        "on-primary-fixed-variant": "#d4cfc6",
        secondary: "#7b9ec4",
        "on-secondary": "#0a1220",
        "secondary-fixed": "#7b9ec4",
        "secondary-fixed-dim": "#4a6d94",
        "on-secondary-fixed": "#0a1220",
        "on-secondary-fixed-variant": "#1a3354",
        "secondary-container": "#1a3354",
        "on-secondary-container": "#7b9ec4",
        tertiary: "#f5f0e8",
        "on-tertiary": "#0a1220",
        "tertiary-container": "#2a2a26",
        "on-tertiary-container": "#9ca3af",
        "on-tertiary-fixed": "#f5f0e8",
        "on-tertiary-fixed-variant": "#4a4a44",
        "tertiary-fixed": "#f5f0e8",
        "tertiary-fixed-dim": "#d4cfc6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        // ── Canvas: LIGHT base (D1). Dark sections must set bg-ink-deep +
        // text-cream explicitly — never rely on inherited colour. ──
        background: "#f4f1ec",
        "on-background": "#0a1220",
        surface: "#f4f1ec",
        "on-surface": "#0a1220",
        "on-surface-variant": "#4b5563",
        "surface-variant": "#ebe7df",
        "surface-dim": "#e2ddd3",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f4ee",
        "surface-container": "#ebe7df",
        "surface-container-high": "#e4dfd5",
        "surface-container-highest": "#dcd6ca",
        "inverse-surface": "#0a1220",
        "inverse-on-surface": "#f5f0e8",
        "inverse-primary": "#7b9ec4",
        "primary-fixed": "#f5f0e8",
        "primary-fixed-dim": "#d4cfc6",
        outline: "#6b7280",
        "outline-variant": "#c9c3b8",
        "surface-tint": "#7b9ec4",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        // Fluid — driven by --multiplier (see globals.css @layer base).
        "margin-edge": "var(--s-margin-edge)",
        "section-gap": "var(--s-section-gap)",
        gutter: "var(--s-gutter)",
        baseline: "4px",
        "container-max": "1440px",
      },
      fontFamily: {
        serif: ["var(--font-newsreader)", "Georgia", "serif"],
        sans: ["var(--font-manrope)", "system-ui", "sans-serif"],
        "stat-display": ["var(--font-newsreader)", "Georgia", "serif"],
        "label-caps": ["var(--font-manrope)", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["var(--font-newsreader)", "Georgia", "serif"],
        "body-md": ["var(--font-manrope)", "system-ui", "sans-serif"],
        "display-hero": ["var(--font-newsreader)", "Georgia", "serif"],
        "headline-md": ["var(--font-newsreader)", "Georgia", "serif"],
        "body-lg": ["var(--font-manrope)", "system-ui", "sans-serif"],
        "headline-lg": ["var(--font-newsreader)", "Georgia", "serif"],
      },
      fontSize: {
        // D7 discipline: line-height 1 on all display type, 1.3 on body.
        // Weights 300 / 400 / 500 only — never 600 or 700.
        "display-hero": [
          "var(--t-display-hero)",
          { lineHeight: "1", letterSpacing: "-0.02em", fontWeight: "300" },
        ],
        "headline-lg": ["var(--t-headline-lg)", { lineHeight: "1", fontWeight: "300" }],
        "headline-lg-mobile": ["var(--t-headline-lg)", { lineHeight: "1", fontWeight: "300" }],
        "headline-md": ["var(--t-headline-md)", { lineHeight: "1", fontWeight: "300" }],
        "stat-display": ["var(--t-stat-display)", { lineHeight: "1", fontWeight: "300" }],
        "body-lg": ["var(--t-body-lg)", { lineHeight: "1.3", fontWeight: "400" }],
        "body-md": ["var(--t-body-md)", { lineHeight: "1.3", fontWeight: "400" }],
        "label-caps": [
          "var(--t-label-caps)",
          { lineHeight: "1.2", letterSpacing: "0.15em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
