/**
 * BMIG portfolio — 12 operating assets.
 *
 * STRUCTURE IS REAL. PROSE IS PLACEHOLDER.
 * Names, addresses, phones, brands, and asset types are confirmed client data.
 * Any field on a property whose `contentStatus` is "placeholder" contains
 * scaffolding copy written to the BMIG thesis — replace before launch.
 *
 * `placeId`, `bookingUrl`, `coordinates`, and `gallery` are populated by
 * `scripts/enrich-properties.mjs` (Google Places API). See docs/MASTER-PLAN.md §8.
 */

import generated from "./places.generated.json";

export type AssetType = "hospitality" | "education" | "residential";

export type GalleryPhoto = {
  src: string;
  alt: string;
  /**
   * Photographer / uploader credit that MUST be displayed alongside the image.
   *
   * Hand-authored photography (client-supplied, franchise media kits) leaves
   * this null — we hold the rights and no credit is required. Photos pulled
   * from the Google Places API carry `authorAttributions`, and Google requires
   * that attribution be shown wherever the image appears. Render it with
   * `<PhotoAttribution>`; do not add a Places-sourced photo to a surface that
   * has nowhere to put the credit.
   */
  attribution?: string | null;
};

/**
 * One line in a property's amenities grid.
 *
 * `icon` is a key into `ui/AmenityIcon.tsx` — an unknown key renders the
 * neutral fallback mark rather than an empty box, so adding a label before its
 * glyph exists degrades quietly.
 *
 * ⚠️ **Amenities are sourced, never assumed.** Everything generated by
 * `scripts/enrich-properties.mjs` traces to something Google explicitly states
 * about the property (its editorial summary, or the accessibility/pets/children
 * booleans). Nothing is inferred from the franchise brand — "it's a Hampton
 * Inn, so it has a business centre" is the exact class of invented fact this
 * project has had to retract before. A hand-authored `amenities` array on a
 * property literal overrides the generated one entirely, which is the intended
 * route for the fuller brand-page lists once someone supplies them.
 */
export type Amenity = {
  label: string;
  icon: string;
};

export type Property = {
  slug: string;
  name: string;
  shortName: string;
  address: string;
  city: string;
  state: string;
  phone: string | null;
  /** Portfolio category — BMIG operates beyond hotels. */
  assetType: AssetType;
  /** Franchise/brand family, or null for independent assets. */
  brand: string | null;
  category: string;
  acquiredYear: string;
  subunit: string;
  /** Deep link to the property's own booking page. Filled by enrichment. */
  bookingUrl: string | null;
  /** Google Places ID. Filled by enrichment; stable, safe to persist. */
  placeId: string | null;
  coordinates: { lat: number; lng: number } | null;
  summary: string;
  longform: string;
  acquisition: string;
  renovation: string;
  operations: string;
  outcomesNote: string;
  homeHeroSrc: string | null;
  homeSatelliteSrc: string | null;
  gallery: GalleryPhoto[];
  /**
   * Filled by enrichment; always an array after `enrich()`. Optional here so
   * the 12 hand-authored literals below don't each need an empty placeholder —
   * set it on a literal only to override what Google returned.
   */
  amenities?: Amenity[];
  /**
   * Where `amenities` came from. Drives the provenance line under the grid.
   *
   * "google" (the default, set by `enrich()`) prints "as published by the
   * property on Google" and links to the operator's page. "client" prints
   * nothing — the claim would be false, and a property we own outright needs
   * no third-party citation. Set this whenever you hand-author `amenities`.
   */
  amenitiesSource?: "google" | "client";
  /**
   * Extra hand-authored facts for the Asset Detail table, rendered after the
   * shared rows (Location, Asset Type, Brand, …).
   *
   * Exists because the shared rows are hotel-shaped, and the group's
   * non-hospitality assets have the facts that actually matter to a reader
   * sitting outside them — lot size, water frontage. Always CLIENT-SUPPLIED;
   * never derived, never inferred from a listing site.
   */
  highlights?: { label: string; value: string }[];
  /** "final" = client-approved copy. "placeholder" = scaffolding, must be replaced. */
  contentStatus: "final" | "placeholder";
};

/** Shared thesis language — used as scaffolding until per-asset copy is written. */
const THESIS = {
  acquisition:
    "Identify underperforming assets in markets whose structural quality exceeds their current operating performance.",
  renovation:
    "Capital deployment into the physical asset, operating model, and brand positioning. We do not hand the keys to a third party.",
  operations:
    "Held and operated directly under Brahmas Hospitality Management. Quarterly performance review against investment thesis.",
  outcomesNote: "Outcomes reported at financial close of fiscal year one.",
} as const;

export const properties: Property[] = [
  // ── 01 ─────────────────────────────────────────────────────────────────────
  // NOTE: slug retained from the original dataset because photography already
  // lives at /properties/clarion-pointe-tampa-brandon/. Do not rename.
  {
    slug: "clarion-pointe-tampa-brandon",
    name: "Clarion Pointe Tampa-Brandon Near Fairgrounds and Casino",
    shortName: "Clarion Pointe Tampa",
    address: "10007 Princess Palm Ave, Tampa, FL 33619",
    city: "Tampa",
    state: "Florida",
    phone: "(813) 622-8557",
    assetType: "hospitality",
    brand: "Choice Hotels",
    category: "Acquisition",
    acquiredYear: "2024",
    subunit: "Brahmas Hospitality Management",
    bookingUrl: null,
    placeId: null,
    coordinates: null,
    summary:
      "Acquired underperforming and repositioned in full. Held and operated under Brahmas Hospitality Management since handover.",
    longform:
      "Located near the Florida State Fairgrounds and the Seminole Hard Rock event corridor, the property benefits from year-round demand drivers. Brahmas acquired the asset and initiated a full operational and physical repositioning on closing.",
    acquisition:
      "Identify underperforming hotels near secular demand drivers whose structure supports long-term performance.",
    renovation:
      "Interior refurbishment, building envelope improvements, operating model reset, and brand repositioning.",
    operations: THESIS.operations,
    outcomesNote: THESIS.outcomesNote,
    homeHeroSrc: "/properties/clarion-pointe-tampa-brandon/01-hero.webp",
    homeSatelliteSrc: "/properties/clarion-pointe-tampa-brandon/02-satellite.webp",
    gallery: [
      {
        src: "/properties/clarion-pointe-tampa-brandon/01-hero.webp",
        alt: "Clarion Pointe Tampa Brandon exterior anchor shot",
      },
      {
        src: "/properties/clarion-pointe-tampa-brandon/02-satellite.webp",
        alt: "Clarion Pointe Tampa Brandon public space",
      },
      {
        src: "/properties/clarion-pointe-tampa-brandon/03-gallery-1.webp",
        alt: "Clarion Pointe Tampa Brandon interior detail",
      },
      {
        src: "/properties/clarion-pointe-tampa-brandon/04-gallery-2.webp",
        alt: "Clarion Pointe Tampa Brandon building exterior",
      },
      {
        src: "/properties/clarion-pointe-tampa-brandon/05-gallery-3.webp",
        alt: "Clarion Pointe Tampa Brandon room interior",
      },
    ],
    contentStatus: "final",
  },

  // ── 02 ─────────────────────────────────────────────────────────────────────
  {
    slug: "quality-inn-conference-center-tampa-brandon",
    // Wording aligned to the Google Business Profile 2026-08-17 ("and", hyphen
    // rather than slash). Same hotel — address and phone both match — but the
    // owner-photo heuristic compares author name to this string, and the
    // missing "and" was enough to reject all 7 of the hotel's own photos.
    name: "Quality Inn and Conference Center Tampa-Brandon",
    shortName: "Quality Inn Conference Center",
    address: "9331 E Adamo Dr, Tampa, FL 33619",
    city: "Tampa",
    state: "Florida",
    phone: "(813) 621-5555",
    assetType: "hospitality",
    brand: "Choice Hotels",
    category: "Acquisition",
    acquiredYear: "2024",
    subunit: "Brahmas Hospitality Management",
    bookingUrl: null,
    placeId: null,
    coordinates: null,
    summary:
      "Conference-oriented asset on the Adamo Drive corridor, held and operated under Brahmas Hospitality Management.",
    longform:
      "A conference and group-demand asset positioned on the Adamo Drive corridor east of downtown Tampa. Meeting space and access to the Selmon Expressway support a mixed base of corporate, group, and transient demand.",
    acquisition: THESIS.acquisition,
    renovation: THESIS.renovation,
    operations: THESIS.operations,
    outcomesNote: THESIS.outcomesNote,
    homeHeroSrc: null,
    homeSatelliteSrc: null,
    gallery: [],
    contentStatus: "placeholder",
  },

  // ── 03 ─────────────────────────────────────────────────────────────────────
  {
    slug: "quality-inn-suites-tampa-east",
    name: "Quality Inn & Suites",
    shortName: "Quality Inn & Suites Tampa",
    address: "4955 E 18th Ave, Tampa, FL 33605",
    city: "Tampa",
    state: "Florida",
    phone: "(813) 623-6000",
    assetType: "hospitality",
    brand: "Choice Hotels",
    category: "Acquisition",
    acquiredYear: "2024",
    subunit: "Brahmas Hospitality Management",
    bookingUrl: null,
    placeId: null,
    coordinates: null,
    summary:
      "East Tampa select-service asset with direct interstate access, operated under Brahmas Hospitality Management.",
    longform:
      "A select-service asset in east Tampa with direct access to I-4 and proximity to the Port of Tampa industrial corridor, supporting a durable base of extended-stay and contractor demand.",
    acquisition: THESIS.acquisition,
    renovation: THESIS.renovation,
    operations: THESIS.operations,
    outcomesNote: THESIS.outcomesNote,
    homeHeroSrc: null,
    homeSatelliteSrc: null,
    gallery: [],
    contentStatus: "placeholder",
  },

  // ── 04 ─────────────────────────────────────────────────────────────────────
  {
    slug: "microtel-inn-suites-zephyrhills",
    name: "Microtel Inn & Suites by Wyndham Zephyrhills",
    shortName: "Microtel Inn & Suites Zephyrhills",
    address: "7839 Gall Blvd, Zephyrhills, FL 33541",
    city: "Zephyrhills",
    state: "Florida",
    phone: "(813) 815-3007",
    assetType: "hospitality",
    brand: "Wyndham",
    category: "Acquisition",
    acquiredYear: "2024",
    subunit: "Brahmas Hospitality Management",
    bookingUrl: null,
    placeId: null,
    coordinates: null,
    summary:
      "Efficient-format asset serving the Zephyrhills and east Pasco County market.",
    longform:
      "An efficient-format asset on the Gall Boulevard corridor serving east Pasco County. The market's healthcare, motorsport, and seasonal residential demand supports year-round occupancy at a low operating cost base.",
    acquisition: THESIS.acquisition,
    renovation: THESIS.renovation,
    operations: THESIS.operations,
    outcomesNote: THESIS.outcomesNote,
    homeHeroSrc: null,
    homeSatelliteSrc: null,
    gallery: [],
    contentStatus: "placeholder",
  },

  // ── 05 ─────────────────────────────────────────────────────────────────────
  {
    slug: "rodeway-inn-port-richey-north",
    name: "Rodeway Inn Port Richey North",
    shortName: "Rodeway Inn Port Richey",
    address: "11810 US Hwy 19, Port Richey, FL 34668",
    city: "Port Richey",
    state: "Florida",
    phone: "(727) 863-3336",
    assetType: "hospitality",
    brand: "Choice Hotels",
    category: "Acquisition",
    acquiredYear: "2024",
    subunit: "Brahmas Hospitality Management",
    bookingUrl: null,
    placeId: null,
    coordinates: null,
    summary:
      "US-19 corridor asset serving west Pasco County, operated under Brahmas Hospitality Management.",
    longform:
      "Positioned on the US-19 corridor in west Pasco County, the asset serves a steady base of coastal leisure, healthcare, and extended-stay demand with a low fixed-cost operating profile.",
    acquisition: THESIS.acquisition,
    renovation: THESIS.renovation,
    operations: THESIS.operations,
    outcomesNote: THESIS.outcomesNote,
    homeHeroSrc: null,
    homeSatelliteSrc: null,
    gallery: [],
    contentStatus: "placeholder",
  },

  // ── 06 ─────────────────────────────────────────────────────────────────────
  // NOTE: slug retained from the original dataset because photography already
  // lives at /properties/hampton-inn-tampa-veterans-expwy/. Do not rename.
  {
    slug: "hampton-inn-tampa-veterans-expwy",
    // NAME CORRECTED 2026-08-17. Was "Hampton Inn & Suites Tampa Airport
    // Westshore" — no "& Suites", and not Westshore. Address (5628 W Waters
    // Ave), phone ((813) 901-5900) and the slug itself all agree with the
    // Google Business Profile name below. Note #8 in this file IS a "Hampton
    // Inn & Suites"; these are two different assets and only that one has
    // suites in its name.
    name: "Hampton Inn Tampa-Veterans Expwy (Airport North)",
    shortName: "Hampton Inn Tampa-Veterans Expwy",
    address: "5628 W Waters Ave, Tampa, FL 33634",
    city: "Tampa",
    state: "Florida",
    phone: "(813) 901-5900",
    assetType: "hospitality",
    brand: "Hilton",
    category: "Acquisition",
    acquiredYear: "2024",
    subunit: "Brahmas Hospitality Management",
    bookingUrl: null,
    placeId: null,
    coordinates: null,
    summary:
      "Acquired underperforming and repositioned in full. Held and operated under Brahmas Hospitality Management since handover.",
    longform:
      "Acquired from a regional operator seeking liquidity. The asset had strong bones and a stable Florida hospitality position, but its operational performance lagged its location grade. Brahmas acquired with the intent to reposition the property under its hospitality model.",
    acquisition:
      "Identify underperforming hotels in prime markets where structural quality exceeds current operating performance.",
    renovation:
      "Building envelope, room interiors, public space modernization, and brand repositioning under capital improvement program.",
    operations: THESIS.operations,
    outcomesNote: THESIS.outcomesNote,
    // These two stills stay hand-authored on purpose: they are the creditless
    // chrome assets the homepage hero and image band draw on (see
    // `ownPhotographyProperties` below). The DETAIL-PAGE gallery below is
    // deliberately empty so enrichment fills it from Places — same photographs,
    // one at 4800x3200, and properly credited.
    homeHeroSrc: "/properties/hampton-inn-tampa-veterans-expwy/01-hero.webp",
    homeSatelliteSrc:
      "/properties/hampton-inn-tampa-veterans-expwy/02-satellite.webp",
    gallery: [],
    contentStatus: "final",
  },

  // ── 07 ─────────────────────────────────────────────────────────────────────
  {
    slug: "holiday-inn-express-orlando-seaworld",
    // NAME CORRECTED 2026-08-17. Was "Holiday Inn Express & Suites Orlando at
    // SeaWorld" — that is a DIFFERENT hotel, at 10771 International Dr, phone
    // (407) 996-4100. Our address (2776 Destination Pkwy) and phone
    // ((407) 640-7500) both match "Holiday Inn Express Orlando - South Park"
    // exactly, per Google Places. Two confirmed fields outvoted the third.
    // The wrong name is why enrichment skipped this asset on every prior run.
    // Slug retained: renaming it would break the /portfolio/… URL.
    name: "Holiday Inn Express Orlando South Park",
    shortName: "Holiday Inn Express Orlando",
    address: "2776 Destination Pkwy, Orlando, FL 32819",
    city: "Orlando",
    state: "Florida",
    phone: "(407) 640-7500",
    assetType: "hospitality",
    brand: "IHG",
    category: "Acquisition",
    acquiredYear: "2024",
    subunit: "Brahmas Hospitality Management",
    bookingUrl: null,
    placeId: null,
    coordinates: null,
    summary:
      "Orlando tourism-corridor asset adjacent to the Orange County Convention Center and SeaWorld.",
    longform:
      "Positioned in the Orlando International Drive tourism corridor, adjacent to the Orange County Convention Center and within reach of SeaWorld. The location captures both leisure and convention-driven demand across the calendar.",
    acquisition: THESIS.acquisition,
    renovation: THESIS.renovation,
    operations: THESIS.operations,
    outcomesNote: THESIS.outcomesNote,
    homeHeroSrc: null,
    homeSatelliteSrc: null,
    gallery: [],
    contentStatus: "placeholder",
  },

  // ── 08 ─────────────────────────────────────────────────────────────────────
  {
    slug: "hampton-inn-suites-tampa-east-seffner",
    name: "Hampton Inn & Suites Tampa East (Casino Area)",
    shortName: "Hampton Inn & Suites Tampa East",
    address: "11740 Tampa Gateway Blvd, Seffner, FL 33584",
    city: "Seffner",
    state: "Florida",
    phone: "(813) 630-4321",
    assetType: "hospitality",
    brand: "Hilton",
    category: "Acquisition",
    acquiredYear: "2024",
    subunit: "Brahmas Hospitality Management",
    bookingUrl: null,
    placeId: null,
    coordinates: null,
    summary:
      "Interstate-adjacent asset serving the Seminole Hard Rock and east Hillsborough corridor.",
    longform:
      "An I-4 adjacent asset in Seffner serving the Seminole Hard Rock casino corridor and east Hillsborough County. Interstate visibility and event-driven demand underpin a resilient occupancy base.",
    acquisition: THESIS.acquisition,
    renovation: THESIS.renovation,
    operations: THESIS.operations,
    outcomesNote: THESIS.outcomesNote,
    homeHeroSrc: null,
    homeSatelliteSrc: null,
    gallery: [],
    contentStatus: "placeholder",
  },

  // ── 09 ─────────────────────────────────────────────────────────────────────
  {
    slug: "clarion-pointe-lakeland-i4",
    name: "Clarion Pointe Lakeland I-4",
    shortName: "Clarion Pointe Lakeland",
    address: "4321 Lakeland Park Dr, Lakeland, FL 33809",
    city: "Lakeland",
    state: "Florida",
    phone: "(863) 577-1170",
    assetType: "hospitality",
    brand: "Choice Hotels",
    category: "Acquisition",
    acquiredYear: "2024",
    subunit: "Brahmas Hospitality Management",
    bookingUrl: null,
    placeId: null,
    coordinates: null,
    summary:
      "I-4 corridor asset positioned between the Tampa and Orlando markets.",
    longform:
      "Positioned on the I-4 corridor between Tampa and Orlando, the asset captures logistics, corporate, and transient demand from one of Florida's most heavily trafficked interstate segments.",
    acquisition: THESIS.acquisition,
    renovation: THESIS.renovation,
    operations: THESIS.operations,
    outcomesNote: THESIS.outcomesNote,
    homeHeroSrc: null,
    homeSatelliteSrc: null,
    gallery: [],
    contentStatus: "placeholder",
  },

  // ── 10 ─────────────────────────────────────────────────────────────────────
  {
    // NOTE: slug retained deliberately. It reads "sleep-inn", which no longer
    // matches the name below, but it is the live /portfolio/ URL and the photo
    // directory path. Same reasoning as the two slugs noted at the top of this
    // file — do not rename.
    slug: "sleep-inn-suites-fort-myers-airport",
    // BRAND CORRECTED 2026-08-17, confirmed by the client. Was "Sleep Inn &
    // Suites Fort Myers Airport" / Choice Hotels. Google's listing for this
    // address and phone is La Quinta (a Wyndham brand), and the client
    // confirmed the asset flies the La Quinta flag.
    name: "La Quinta Inn and Suites Fort Myers I-75",
    shortName: "La Quinta Inn & Suites Fort Myers",
    address: "9521 Market Place Rd, Fort Myers, FL 33912",
    city: "Fort Myers",
    state: "Florida",
    phone: "(941) 585-0973",
    assetType: "hospitality",
    brand: "Wyndham",
    category: "Acquisition",
    acquiredYear: "2024",
    subunit: "Brahmas Hospitality Management",
    bookingUrl: null,
    placeId: null,
    coordinates: null,
    summary:
      "Southwest Florida asset serving the Fort Myers airport and Gulf coast market.",
    longform:
      "A southwest Florida asset serving Southwest Florida International Airport and the surrounding Gulf coast market, with demand supported by seasonal leisure travel and regional business activity.",
    acquisition: THESIS.acquisition,
    renovation: THESIS.renovation,
    operations: THESIS.operations,
    outcomesNote: THESIS.outcomesNote,
    homeHeroSrc: null,
    homeSatelliteSrc: null,
    gallery: [],
    contentStatus: "placeholder",
  },

  // ── 11 ─────────────────────────────────────────────────────────────────────
  {
    // Slug retained — it is the live /portfolio/ URL. The asset was listed to us
    // only as "Beach House" until the client identified it 2026-08-17.
    slug: "beach-house-weeki-wachee",
    // NAME from the client: listed as "Beach House". Same parcel as the
    // Zillow listing 10492 Pine Island Dr, Weeki Wachee, FL 34607
    // (zpid 44796785) — 5.1-acre lot confirmed. Previously displayed as
    // Serenity Cove.
    name: "Beach House",
    shortName: "Beach House",
    address: "10492 Pine Island Dr, Weeki Wachee, FL 34607",
    city: "Weeki Wachee",
    state: "Florida",
    phone: null,
    assetType: "residential",
    brand: null,
    category: "Residential",
    acquiredYear: "2024",
    subunit: "Brahmas Management and Investment Group",
    bookingUrl: null,
    placeId: null,
    // Geocode for the exact address, from the Places API 2026-08-17. Hand-set
    // because enrichment cannot reach this property — see the note on
    // `gallery` below.
    coordinates: { lat: 28.5759429, lng: -82.6530071 },
    summary:
      "Private Gulf-front estate on Pine Island — 5.1 acres with more than 600 feet of water frontage, held directly by the group.",
    longform:
      "The Beach House occupies 5.1 acres on Pine Island in Weeki Wachee, with more than 600 feet of frontage on the Gulf of Mexico. The estate sits on Florida's Nature Coast and is held directly by Brahmas Management and Investment Group rather than under the hospitality management arm — the group's only residential holding, and the only asset in the portfolio it does not operate for guests.",
    highlights: [
      { label: "Lot Size", value: "5.1 acres" },
      { label: "Water Frontage", value: "600+ feet" },
      { label: "Waterway", value: "Gulf of Mexico" },
    ],
    /**
     * HAND-AUTHORED — the only property in the file with a client-sourced list.
     *
     * Google Places has no listing for a private residence, so `deriveAmenities()`
     * has nothing to work from. These come from two places, both legitimate,
     * and NEITHER is franchise-brand inference:
     *
     *   · CLIENT-STATED — Gulf frontage, acreage. Supplied 2026-08-17.
     *   · VISIBLE IN THE CLIENT'S OWN PHOTOGRAPHS — the two residences, the
     *     dock, the pond and the covered parking are all plainly in the aerial
     *     (01) and the elevation (04). The wraparound porch is the subject of
     *     (06).
     *
     * ⚠️ "Two Residences" is the one worth confirming: the aerial shows a second
     * house on the same driveway loop, which reads as a guest house on the same
     * parcel — but a neighbouring property on a shared drive would look
     * identical from above. Ask before treating it as a selling point.
     *
     * `amenitiesSource: "client"` suppresses the "as published on Google"
     * provenance line, which would be false here.
     */
    amenitiesSource: "client",
    amenities: [
      { label: "600+ ft Gulf Frontage", icon: "waterfront" },
      { label: "5.1-Acre Grounds", icon: "acreage" },
      { label: "Private Dock", icon: "dock" },
      { label: "Two Residences", icon: "residence" },
      { label: "Wraparound Porch", icon: "porch" },
      { label: "Freshwater Pond", icon: "pond" },
      { label: "Covered Parking", icon: "parking" },
    ],
    acquisition:
      "Selective acquisition of residential assets in coastal Florida markets with constrained supply.",
    renovation:
      "Capital improvement to the physical asset consistent with the group's standards.",
    operations: "Held directly by Brahmas Management and Investment Group.",
    outcomesNote: THESIS.outcomesNote,
    /**
     * Deliberately null, even though a gallery now exists below.
     *
     * `enrich()` falls back to `gallery[0].src`, so the portfolio card and the
     * detail-page hero band both still work. What staying null does is keep
     * this property OUT of `ownPhotographyProperties`, which selects on a
     * HAND-AUTHORED `homeHeroSrc` — so these images cannot reach the homepage
     * hero or image band.
     *
     * That is intentional: the photographs carry a visible **StellarMLS**
     * watermark and one carries a **"© Chris Watkins"** photographer credit.
     * Fine on a portfolio detail page the client has signed off; a different
     * decision to put on the homepage. To opt in later, set this to
     * "/properties/beach-house-weeki-wachee/01-hero-aerial.webp".
     */
    homeHeroSrc: null,
    homeSatelliteSrc: null,
    /**
     * Client-supplied from the property's Zillow listing (zpid 44796785),
     * 2026-08-17. **The client states the group holds full rights to these
     * images.** That assertion is theirs to make — see the note above about
     * the MLS watermark and photographer credit still burned into the files.
     *
     * ⚠️ HAND-AUTHORED ON PURPOSE, and it must stay that way:
     *   · `enrich()` keeps a non-empty `gallery`, so these can never be
     *     overwritten by a `--photos` run.
     *   · `readProperties()` in the enrichment script now sees a non-empty
     *     `gallery: [{`, so `hasOwnPhotos` is true and the script will not
     *     burn Place Photo quota on this slug.
     *   · `attribution: null` means <PhotoAttribution> renders nothing —
     *     correct for imagery we hold rights to, unlike the Places-sourced
     *     galleries elsewhere in this file which all carry an owner credit.
     *
     * Google Places cannot help here regardless: a private residence has no
     * business listing, the address returns a bare geocode with zero photos,
     * and "Serenity Cove" matches no place at all. The nearest named results
     * are a public county park and an unrelated vacation rental — **never
     * force a match to either.**
     *
     * Order is deliberate: aerial establishing shot, approach, the two
     * structures, elevations, then porches and interior.
     */
    gallery: [
      {
        src: "/properties/beach-house-weeki-wachee/01-hero-aerial.webp",
        alt: "Aerial view of the Beach House — the estate on its Pine Island peninsula, Gulf of Mexico on three sides",
        attribution: null,
      },
      {
        src: "/properties/beach-house-weeki-wachee/02-approach.webp",
        alt: "The approach to the main residence beneath a canopy of live oaks and palms",
        attribution: null,
      },
      {
        src: "/properties/beach-house-weeki-wachee/03-estate.webp",
        alt: "Main residence and guest house across the estate's central lawn",
        attribution: null,
      },
      {
        src: "/properties/beach-house-weeki-wachee/04-elevation.webp",
        alt: "Front elevation of the main residence, raised over covered parking",
        attribution: null,
      },
      {
        src: "/properties/beach-house-weeki-wachee/05-aerial-oblique.webp",
        alt: "Elevated three-quarter view of the main residence and surrounding grounds",
        attribution: null,
      },
      {
        src: "/properties/beach-house-weeki-wachee/06-porch.webp",
        alt: "Wraparound porch running the length of the residence, overlooking the Gulf",
        attribution: null,
      },
      {
        src: "/properties/beach-house-weeki-wachee/07-deck.webp",
        alt: "Deck seating with an open view across the Gulf of Mexico",
        attribution: null,
      },
      {
        src: "/properties/beach-house-weeki-wachee/08-porch-gulf.webp",
        alt: "Covered porch looking out over the water frontage",
        attribution: null,
      },
      {
        src: "/properties/beach-house-weeki-wachee/09-interior.webp",
        alt: "Open kitchen and dining area with hardwood floors",
        attribution: null,
      },
    ],
    contentStatus: "placeholder",
  },

  // ── 12 ─────────────────────────────────────────────────────────────────────
  {
    slug: "primrose-school-of-oldsmar",
    name: "Primrose School of Oldsmar",
    shortName: "Primrose School of Oldsmar",
    address: "3760 Tampa Rd, Oldsmar, FL 34677",
    city: "Oldsmar",
    state: "Florida",
    phone: "(813) 818-1102",
    assetType: "education",
    brand: "Primrose Schools",
    category: "Education",
    acquiredYear: "2024",
    subunit: "Brahmas Management and Investment Group",
    bookingUrl: null,
    placeId: null,
    coordinates: null,
    summary:
      "Early education asset in Oldsmar, extending the group's operating model beyond hospitality.",
    longform:
      "An accredited early education and childcare asset serving the Oldsmar and north Pinellas market. The asset extends the group's operating discipline into education real estate, where demand is driven by long-term demographic rather than travel cycles.",
    acquisition:
      "Extend the operating model into education real estate, where demand is demographically rather than cyclically driven.",
    renovation:
      "Capital improvement to facilities consistent with brand standards and licensing requirements.",
    operations:
      "Held and operated under Brahmas Management and Investment Group with brand-standard oversight.",
    outcomesNote: THESIS.outcomesNote,
    homeHeroSrc: null,
    homeSatelliteSrc: null,
    gallery: [],
    contentStatus: "placeholder",
  },
];

/* ────────────────────────────────────────────────────────────────────────────
   Google Places enrichment overlay
   ────────────────────────────────────────────────────────────────────────────
   `places.generated.json` is written by scripts/enrich-properties.mjs and is
   safe to delete/regenerate. It only fills FACTUAL fields that are still empty
   above — it can never overwrite hand-written prose, and an existing hand-set
   value always wins. Gallery photos are appended only when we have none.
   ──────────────────────────────────────────────────────────────────────────── */

type GeneratedPlace = {
  placeId?: string | null;
  verifiedAddress?: string | null;
  phone?: string | null;
  bookingUrl?: string | null;
  coordinates?: { lat: number; lng: number } | null;
  photos?: { src: string; attribution?: string | null }[];
  amenities?: Amenity[];
};

const placesData = generated as Record<string, GeneratedPlace>;

function enrich(p: Property): Property {
  const g = placesData[p.slug];
  if (!g) return { ...p, amenities: p.amenities ?? [] };

  const photos = g.photos ?? [];
  const gallery: GalleryPhoto[] =
    p.gallery.length > 0
      ? p.gallery
      : photos.map((photo, i) => ({
          src: photo.src,
          alt: `${p.shortName} — photograph ${i + 1}`,
          // Carried through so the gallery can render the required credit.
          attribution: photo.attribution ?? null,
        }));

  return {
    ...p,
    // Hand-authored values always take precedence.
    phone: p.phone ?? g.phone ?? null,
    placeId: p.placeId ?? g.placeId ?? null,
    bookingUrl: p.bookingUrl ?? g.bookingUrl ?? null,
    coordinates: p.coordinates ?? g.coordinates ?? null,
    gallery,
    // A hand-authored list replaces the generated one wholesale rather than
    // merging — a curated set would otherwise be silently padded with whatever
    // Google happened to say.
    amenities: p.amenities ?? g.amenities ?? [],
    // Anything hand-authored is client-sourced unless it says otherwise; the
    // generated path is Google by definition.
    amenitiesSource: p.amenities ? (p.amenitiesSource ?? "client") : "google",
    homeHeroSrc: p.homeHeroSrc ?? gallery[0]?.src ?? null,
  };
}

/** The portfolio, with Places data overlaid. Import this everywhere. */
export const enrichedProperties: Property[] = properties.map(enrich);

/**
 * A property guaranteed to have imagery — `homeHeroSrc` is non-null and the
 * gallery is non-empty, so consumers can render images without null checks.
 */
export type FeaturedProperty = Property & { homeHeroSrc: string };

/** Assets with photography ready — safe to feature on the homepage. */
export const featuredProperties: FeaturedProperty[] = enrichedProperties.filter(
  (p): p is FeaturedProperty => p.gallery.length > 0 && p.homeHeroSrc !== null
);

/**
 * Assets with a HAND-HELD chrome still, safe on surfaces that cannot show a
 * credit — the homepage hero, the image band, marquees, section backdrops.
 *
 * Use this, never `featuredProperties`, for those surfaces. `enrich()` falls
 * back to `gallery[0].src` for `homeHeroSrc`, so with Places photos in the data
 * that fallback can quietly promote an attributed photograph onto the hero,
 * where the composition has no room for a credit and we would be displaying it
 * in breach of the attribution requirement. Selecting by construction makes
 * that impossible rather than relying on everyone remembering.
 *
 * ── Why this reads the RAW literals, not the enriched list ───────────────────
 * It used to be `featuredProperties.filter(p => p.gallery.every(no attribution))`
 * — inferring "creditless" from the gallery. That broke on 2026-08-17 when
 * Hampton Inn's detail-page gallery moved to Places while it kept its
 * hand-held chrome stills: the gallery became attributed, so the inference
 * dropped a property whose hero still was perfectly usable, and the homepage
 * image band silently fell to a single image.
 *
 * A hand-authored `homeHeroSrc` on the raw `properties` array is the direct
 * statement of the thing we actually care about — a file we hold ourselves,
 * independent of whatever the gallery is sourced from. `enrich()` preserves it
 * (`p.homeHeroSrc ?? gallery[0]?.src`), so the enriched record still carries
 * the same path.
 *
 * ⚠️ Adding a property here means asserting we can display its hero still with
 * no credit. Do not add one whose image came from a Places download.
 */
const handHeldChromeSlugs = new Set(
  properties.filter((p) => p.homeHeroSrc !== null).map((p) => p.slug)
);

export const ownPhotographyProperties: FeaturedProperty[] =
  featuredProperties.filter((p) => handHeldChromeSlugs.has(p.slug));

export const propertiesByType = (type: AssetType) =>
  enrichedProperties.filter((p) => p.assetType === type);

export const getProperty = (slug: string) =>
  enrichedProperties.find((p) => p.slug === slug);

/**
 * The assets either side of `slug` in portfolio order, for prev/next links.
 *
 * Wraps at both ends, so the last asset's "next" is the first. A detail page is
 * a dead end otherwise — there is no other route out except the navbar.
 */
export function getAdjacentProperties(slug: string): {
  previous: Property | null;
  next: Property | null;
} {
  const i = enrichedProperties.findIndex((p) => p.slug === slug);
  if (i === -1 || enrichedProperties.length < 2) {
    return { previous: null, next: null };
  }
  const n = enrichedProperties.length;
  return {
    previous: enrichedProperties[(i - 1 + n) % n],
    next: enrichedProperties[(i + 1) % n],
  };
}

export const assetTypeLabels: Record<AssetType, string> = {
  hospitality: "Hospitality",
  education: "Education",
  residential: "Residential",
};
